export enum ScreenName {
  WELCOME_SCREEN = "welcome",
  SIGN_IN_SCREEN = "sign-in",
  CREATE_ACCOUNT_SCREEN = "create-account",
  VALIDATE_OTP_SCREEN = "validate-otp",
  HOME_SCREEN = "home",
  TRANSACTION_HISTORY = "transaction-history",
  TRANSACTION_DETAILS = "transaction-details",
  BUDGET_LIST = "budget-list",
  EDIT_USER = "edit-user",
  SELECT_WALLET_LIST = "select-wallet-list",
  SELECT_CATEGORY = "select-category-list",
  SELECT_CATEGORY_ICON = "select-category-icon",
  ADD_WALLET = "add-wallet",
  CATEGORY_LIST = "category-list",
}
